# Generated by Django 6.0.6 on 2026-07-02 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('image', 'Image')], default='text', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
